version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blogging_platform
      POSTGRES_USER: sakshi
      POSTGRES_PASSWORD: Sakshi@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DATABASE_URL: postgres://sakshi:Sakshi@123@db:5432/blogging_platform

volumes:
  postgres_data:

networks:
  app-network:
